# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 10

version: "{build}"

build: off

deploy: off

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm set progress=false
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm -g install yarn
  - yarn config set no-progress
  - yarn

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn test
